global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Quantum HVAC API metrics
  - job_name: 'quantum-hvac-api'
    static_configs:
      - targets: ['quantum-hvac-api:8001']
    metrics_path: /metrics
    scrape_interval: 15s
    scrape_timeout: 10s

  # Dashboard metrics
  - job_name: 'quantum-hvac-dashboard'
    static_configs:
      - targets: ['quantum-hvac-dashboard:8080']
    metrics_path: /api/metrics/prometheus
    scrape_interval: 30s

  # Redis metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']

  # PostgreSQL metrics
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']

  # System metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # Container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']